### ISSUE TITLE
.vscode/settings.json is missing on the template

### ISSUE THREAD

**Issue by keiser1080** [gotofritz/cookiecutter-gotofritz-poetry#1]
cookiecutter gh:gotofritz/cookiecutter-gotofritz-poetry --no-input
...
Installing the current project: new-project (0.1.0)
sed: can't read .vscode/settings.json: No such file or directory
rm: cannot remove '.vscode/settings.json.bak': No such file or directory
...

**Comment by gotofritz** [comment]
Should be fixed - I didn't realise they hadn't been added to the repo because I had a .gitignore in my home folder, which overrules everything. Thanks for the heads up!
